export * from "./AutomaticStart";
export * from "./DinamicTabs";
export * from "./Languages";
export * from "./Theme";
export * from "./interfaces/automaticStart";
export * from "./interfaces/dinamicTabs";
export * from "./interfaces";
export * from "./interfaces/languages";
export * from "./interfaces/theme";
